right_format = """$kubernetes"""
palette = "catppuccin_mocha"
scan_timeout = 10000
command_timeout = 10000

add_newline = true

[directory]
truncate_to_repo = true

[terraform]
disabled = true

[java]
disabled = true

[package]
disabled = true

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style)'
disabled = false
contexts = [
  { context_pattern = '.*dev-eu-aug23', context_alias = 'dev-eu-aug23', style = 'green' },
  { context_pattern = '.*staging-eu-aug23', context_alias = 'staging-eu-aug23', style = 'yellow' },
  { context_pattern = '.*production-eu-aug23', context_alias = 'production-eu-aug23', style = 'red' },
  { context_pattern = '.*cicd-eu-aug23', context_alias = 'cicd-eu-aug23', style = 'purple' }
]

[nix_shell]
disabled = false
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [☃️ $state( \($name\))](bold blue) '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
